### ISSUE TITLE
Import of pypdf

### ISSUE THREAD

**Issue by ycopin** [dcmvdbekerom/pypdfplot#14]
Hi, thanks for this very promising package I just discovered. I tried to install and use, and got the following error:
```
  File "/home/ycopin/Softwares/VirtualEnvs/Python3/lib/python3.5/site-packages/pypdfplot/classes.py", line 35, in <module>
    from pypdf import PdfFileWriter,PdfFileReader
```
I guess this is because the installation of pypdfplot-0.5.0 prompted the installation of PyPDF4-1.27.0 from pypi, which still imports as `PyPDF4`. I had to specifically install master version of PyPDF4 (using `pip install https://github.com/claird/PyPDF4/archive/master.zip`) to make it work.

**Comment by dcmvdbekerom** [comment]
Hello @ycopin ! Thank you for your interest in this package, you're the first person to use it (that I know of) other than myself so welcome! I didn't realize PyPDF4 hadn't released their latest changes yet, It's kind of annoying because some time ago I changed everything from ``PyPDF4`` to ``pypdf`` to make it future-compatible... I guess I forgot to make it present-compatible in the process. Should be an easy fix, thanks for letting me know!

See https://github.com/dcmvdbekerom/pypdfplot/commit/9637bda31c93b5b8645d7f1e88a54a47a2c33f90

**Comment by dcmvdbekerom** [comment]
Fixed in https://github.com/dcmvdbekerom/pypdfplot/commit/c331f4d6cad755b9e85419469e1dd44f96032113
